# Generated by Django 5.1.5 on 2025-01-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productsku_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='size',
        ),
    ]
