# Generated by Django 5.1.5 on 2025-01-23 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsku_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.attributevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together={('product', 'size', 'color')},
        ),
    ]
